id: spark
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: spark
    containers:
      - name: spark
        image: jayunit100/spark2
        command:
           - /bin/bash
           - /opt/run.sh
        cpu: 1000
        ports:
          - name: sp
            containerPort: 7077
labels:
  name: spark-master

